/// Flutter icons location_outline
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  location_outline
///      fonts:
///       - asset: fonts/location_outline.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'location_outline';
  static const _kFontPkg = null;

  static const IconData location_outline =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
